#+TITLE: BlablaMovie

The user chooses the movie she loves the most.

* Specs

In =/specs=, you'll find useful TLA+ specifications for the project.

A specification of what BlablaMovie should do at a high level
is available [[file:specs/blablamovie.pdf][here]].

* Backend

The REST API in =/backend= handles calls to OMDb to search existing movies.

** Database setup

Have an local instance of postgresql running. Create a database named
=blablamovie= and change the login information in [[file:backend/src/app.module.ts][the app module]] with the
correct one:

#+BEGIN_SRC typescript
username: 'postgres',
password: 'admin',
#+END_SRC

** Start

#+BEGIN_SRC sh
npm run start:dev
#+END_SRC

* Frontend

A react App is developed in =/frontend=.

* Road map

** TODO control of votes left on the backend

The backend should check whether the user have enough votes
left for the current week. It's done on frontend for now.

** TODO check that all API entries are safe from attacks

The REST API endpoints should treat safe input.

** DONE Improve err messages on register/login

** DONE add number of votes for winner page

** TODO add 2nd/3rd place

** TODO Fix mobile version css

** TODO Add tests for REST API
